name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Game Contribution Grid
        uses: Platane/snk@master
        with:
          github_user_name: nasablueberry
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push Contribution Grid Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
