name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Game Contribution Grid
        uses: Platane/graph-snake@v2
        with:
          github_user_name: nasablueberry
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push Contribution Grid Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
